version: "3"

services:
  server:
    build: .
    command: python app.py
    ports:
    - "5000:5000"
    volumes:
    - .:/server
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
    - ./config/redis/conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
